### ISSUE TITLE
Improve performance for large grammars

### ISSUE THREAD

**Issue by pschiffmann** [mdaines/grammophone#2]
Hi!

I just tried to analyze [this C grammar](https://www.lysator.liu.se/c/ANSI-C-grammar-y.html) – "just" being an hour ago, and my Chrome tab has by now allocated >600mb for JS stack memory. ;-)

Rationale: I'm a CS student and I recently heard that (canonical) LR(1) parsers weren't suitable for real world usage because of their huge parser tables. So, to get a better impression of what "huge" actually means, I wanted to look at a real world example, instead of those tiny grammars you see during lectures.

Best regards,
Philipp

**Comment by Levalicious** [comment]
One of the biggest bottlenecks that shows up in the Chromium profiler seems to be the repeated sorting of the queue array in one of the functions. I've made a pull request (#12 )  replacing that with a priority queue, and I've noticed a 40x improvement in performance on some small grammars I've been working with. I assume the difference would be even more dramatic in your case, although I'm not sure what the memory overhead is like.

**Comment by mdaines** [comment]
I've made a change that should address this: fadd52228273fb53e3472ee0e7ecfd2ed34f1dd0

The analysis for the C grammar now displays in a few seconds for me, rather than appearing to never finish.

[c-grammar.txt](https://github.com/mdaines/grammophone/files/6900461/c-grammar.txt)
