### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by gonensel** [mdaines/grammophone#28]
hello 
I am trying to analyze this grammar:
E -> T A .
A -> + T A .
A -> .
T -> F B .
B -> * F B .
B -> .
F -> ( E ) .
F -> id .
but I an getting error.
the grammar is ok can you please help?

**Comment by mdaines** [comment]
Symbols like `+` need to be quoted. So the grammar should be written like this:

```
E -> T A .
A -> "+" T A .
A -> .
T -> F B .
B -> "*" F B .
B -> .
F -> "(" E ")" .
F -> id .
```

[Analyze this grammar in Grammophone](https://mdaines.github.io/grammophone/?s=RSAtPiBUIEEgLgpBIC0+ICIrIiBUIEEgLgpBIC0+IC4KVCAtPiBGIEIgLgpCIC0+ICIqIiBGIEIgLgpCIC0+IC4KRiAtPiAiKCIgRSAiKSIgLgpGIC0+IGlkIC4K)
