### ISSUE TITLE
Highlight locally ambiguous nodes in the automaton view.

### ISSUE THREAD

**Issue by modulovalue** [mdaines/grammophone#37]
I think it would be helpful if the "Automaton" views would give nodes a different background color (e.g., red) if any of the cells in their table view are locally ambiguous (that is, if there is an R/R or S/R conflict).

To be more concrete:

<img width="562" alt="Screenshot 2023-11-06 at 13 16 46" src="https://github.com/mdaines/grammophone/assets/24444584/63e6257d-01e5-4e5c-9d51-4bcfd1ea27f0">

Since State 6 is inadequate, it would be helpful if State 6 could have a red background in the automaton view, too.

<img width="619" alt="Screenshot 2023-11-06 at 13 24 31" src="https://github.com/mdaines/grammophone/assets/24444584/55ba58bf-75d3-4836-9a52-1813b58c6b02">

**Comment by mdaines** [comment]
Seems like a good idea. I'll take a closer look in a week or two.

**Comment by mdaines** [comment]
I'm working on this in PR #38.

**Comment by mdaines** [comment]
I just deployed the changes in that PR.
