### ISSUE TITLE
LR(0) fails to display an R/R conflict?

### ISSUE THREAD

**Issue by modulovalue** [mdaines/grammophone#41]
Consider the following grammar:

```
S -> E.
E -> E.
```

[On grammophone](https://mdaines.github.io/grammophone/?s=UyAtPiBFLgpFIC0+IEUu)

It looks like there's a bug with this grammar:

<img width="578" alt="Screenshot 2024-02-02 at 23 33 04" src="https://github.com/mdaines/grammophone/assets/24444584/0454e161-5f32-42bb-a433-bdea3673abb0">

Since SLR(1), LALR(1) and LR(1) are strictly more expressive than LR(0), it looks to me like they should never not recognize a grammar that LR(0) can recognize.

It seems that LR(0) should show an R/R conflict here, but it doesn't:

<img width="293" alt="Screenshot 2024-02-02 at 23 35 25" src="https://github.com/mdaines/grammophone/assets/24444584/b518b127-4681-4289-8fa8-5e6b9b0c14ae">

LALR(1), for example, does show an R/R conflict:

<img width="357" alt="Screenshot 2024-02-02 at 23 36 30" src="https://github.com/mdaines/grammophone/assets/24444584/016b1265-2307-4568-9b14-84a5942eff82">

**Comment by mdaines** [comment]
It looks like the U of C tool gives the expected results then? http://smlweb.cpsc.ucalgary.ca/lr0.php?grammar=S+-%3E+E.%0AE+-%3E+E.&substs=

I don't remember why there isn't any column for end of input in the LR(0) table.

Just to be clear though, this is supposed to be a cyclic grammar?

**Comment by modulovalue** [comment]
> I don't remember why there isn't any column for end of input in the LR(0) table.

Oh, I missed that there's no column for `$`, that has to be it.
Maybe the LR(0) construction is just missing some `alphabet.add("$");` invocation? 

> Just to be clear though, this is supposed to be a cyclic grammar?

All I can say is that I did not intend to test any specific grammar, this discovery was just an accident.

**Comment by mdaines** [comment]
I've deployed the changes referenced above. Thank you for pointing this out!
