### ISSUE TITLE
Spaces are replaced with `⬚`.

### ISSUE THREAD

**Issue by modulovalue** [mdaines/grammophone#46]
Consider:

```
S -> "foo bar".
```

[On Grammophone](https://mdaines.github.io/grammophone/?s=UyAtPiAiZm9vIGJhciIu)

<img width="567" alt="Screenshot 2024-02-08 at 00 15 20" src="https://github.com/mdaines/grammophone/assets/24444584/7c7947af-b62a-4446-a39b-729736f3da82">

Notice how the space character is not a space character (or some placeholder such as `␣`), but `⬚`.

**Comment by mdaines** [comment]
It is actually a placeholder I chose: https://github.com/mdaines/grammophone/blob/1fe29c76b6cb6ace8213fac95d97f9233da3f6f8/src/components/helpers.js#L6

The replacement is done here: https://github.com/mdaines/grammophone/blob/1fe29c76b6cb6ace8213fac95d97f9233da3f6f8/src/components/helpers.js#L47

Something like a middle dot in a different color might be clearer, for example:

<img width="83" alt="Screenshot 2024-02-07 at 8 06 52 PM" src="https://github.com/mdaines/grammophone/assets/1383/46605763-e649-498a-98f5-61e9e2f59c28">

**Comment by mdaines** [comment]
Another example that should maybe be different:

https://mdaines.github.io/grammophone/?s=UyAtPiAiZm9vIFwKYmFyIi4=

```
S -> "foo \
bar".
```

<img width="224" alt="Screenshot 2024-02-07 at 8 14 15 PM" src="https://github.com/mdaines/grammophone/assets/1383/d02c75a6-ea8a-4003-a28f-ddbe35d6b6f6">

**Comment by modulovalue** [comment]
Oh, I see. 

FYI: about escaping newlines, there are special characters for that: https://www.compart.com/en/unicode/block/U+2400, e.g., ␤ 

about escaping spaces, see: https://en.wikipedia.org/wiki/␣

<img width="962" alt="Screenshot 2024-02-08 at 12 44 00" src="https://github.com/mdaines/grammophone/assets/24444584/6fb49c8d-1b55-4b71-8703-01abfbabefc0">

**Comment by mdaines** [comment]
> about escaping spaces, see: [https://en.wikipedia.org/wiki/␣](https://en.wikipedia.org/wiki/%E2%90%A3)

Somehow I'd never noticed that. But curiously, this week I noticed that a paper used ␣ for spaces. So it does seem like a good choice in this context.

**Comment by mdaines** [comment]
I've deployed #48 which should address this.
