### ISSUE TITLE
oth-lr0-3.cfg is defect

### ISSUE THREAD

**Issue by daxim** [mdaines/grammophone#8]
<https://github.com/mdaines/grammophone/blob/master/test/fixtures/example_grammars.json#L80>

It's the only one among the test grammars that has non-reachable rules, this makes me think it's not intended. It was already that way when you imported it:

<http://smlweb.cpsc.ucalgary.ca/vital-stats.php?grammarfile=example-grammars/oth-lr0-3.cfg>

**Comment by mdaines** [comment]
I think I included that example mainly to test that smlweb's examples would parse, so it's not included by mistake. Grammophone doesn't use the same convention that capital letters are nonterminals -- a symbol is a nonterminal only if it is the head of a rule.
