### ISSUE TITLE
On shape = record in viz

### ISSUE THREAD

**Issue by seeidea** [mdaines/grammophone#9]
Hello, mdaines. Because viz issue is closed, I'm here to ask questions.

digraph G{
    graph [rankdir="BT"];
    node[shape="record"];
    a[label="{a}"];
    b[label="{b}"];
    c[label="{c}"];
   
    {rank=same; c; a}; //As long as there is this sentence, it can't be interpreted.  When shape="record"
    b->a;
    c->a;
}

**Comment by mdaines** [comment]
I am not supporting Viz.js anymore.

As far as this graph goes, I suggest looking at the warnings given when you use the `dot` command-line. This may not be specifically a Viz.js issue.
